#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""create index on referenced_records"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0bc0a6ee1bc0'
down_revision = '2f5368ff6d20'
branch_labels = ()
depends_on = '07fb52561c5c'


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        create or replace function referenced_records(json jsonb) returns text[] as  $$
        select 
                array_agg(
                  split_part(
                    reference_arr->'record'->>'$ref',E'literature/',2
                  )
                )  as result
         from 
            jsonb_array_elements(json->'references') as reference_arr; $$
        language sql IMMUTABLE
    ''')
    op.execute('''
        create index ix_records_metadata_json_referenced_records
            on records_metadata
            using gin(referenced_records(json))
    ''')

    op.execute('''
        create or replace function count_ciatations(ids text) returns bigint as $$
        select count(id) as citations_count from records_metadata
            where referenced_records(json) @> ARRAY[ids]; $$
        language sql IMMUTABLE
    ''')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('drop index if exists ix_records_metadata_json_referenced_records')
    op.execute('drop function if exists referenced_records(json jsonb)')
    op.execute('drop function if exists count_citations(ids text)')
    # ### end Alembic commands ###
