name: Build and release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  APP_SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://inspirehep:inspirehep@localhost:5432/inspirehep
  APP_CELERY_BROKER_URL: pyamqp://guest:guest@localhost:5672//
  APP_CELERY_RESULT_BACKEND: redis://localhost:6379/1
  APP_CACHE_REDIS_URL: redis://localhost:6379/0
  APP_ACCOUNTS_SESSION_REDIS_URL: redis://localhost:6379/2
  APP_SEARCH_ELASTIC_HOSTS: localhost

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
        suite: ["test-database test-indexer test-rabbitmq test-redis"]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: inspirehep
          POSTGRES_PASSWORD: inspirehep
          POSTGRES_DB: inspirehep
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
      elasticsearch:
        image: inspirehep/elasticsearch:7.1.1
        env:
          bootstrap.memory_lock: true
          ES_JAVA_OPTS: -Xms1024m -Xmx1024m
          discovery.type: single-node
        ports:
          - 9200:9200

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v4
        with:
            oetry-version: 1.1.0
      - name: Cache poetry env
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ github.sha }}
      - name: Install requirements
          shell: bash
          run: poetry install
      - name: Run tests
        run: py.test tests/integration/workflows
